export const MSG = {
  ERROR_MSG: {
    COMMA_AFTER_LABEL: 'Node label must follow the comma.',
    SELF_REFERENCE: 'Node cannot reference itself.',
    DUPLICATE_REFERENCE: 'Duplicate node label reference.',
    DUPLICATE_STYLE: 'Duplicate style option.',
    DUPLICATE_COLOR: 'Duplicate color option.',
    DUPLICATE_ARROW: 'Duplicate arrow option.',
    INVALID_CONN_OPTION: 'Invalid connection option.',
    MISSING_OPEN_BRACE: 'Opening brace required to start block.',
    MISSING_NODE_NAME: 'Node name required.',
    DUPLICATE_NODE_NAME: 'Duplicate node name.',
    MISSING_KEYWORD: 'Keyword required.',
    DUPLICATE_KEYWORD: 'Keyword already declared.',
    INVALID_KEYWORD: 'Invalid keyword.',
    INVALID_BRACE_LOCATION: 'Braces only allowed in content keyword.',
    UNMATCHED_CLOSE_BRACE: 'Closing brace without opening brace.',
    INVALID_REFERENCE: 'Reference to non-existent node.',
  },
}
